apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    app: deployment

spec:
  revisionHistoryLimit: 3

  selector:
    matchLabels:
      app: java-app

  template:
    metadata:
      labels:
        app: java-app

    spec:
      containers:
        - image: celeguim/jvminfo:latest
          name: jvminfo
          env:
          - name: JAVA_OPTS
            value: -XX:MaxRAMPercentage=60 -XX:InitialRAMPercentage=50 -XX:MinRAMPercentage=30 -XX:+UseContainerSupport
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 200m
              memory: 300Mi
