apiVersion: apps/v1
kind: Deployment

metadata:
  name: deployment
  labels:
    app: deployment

spec:
  revisionHistoryLimit: 3

  selector:
    matchLabels:
      app: java-app1

  template:
    metadata:
      labels:
        app: java-app1

    spec:
      containers:
        - image: celeguim/java-app1:latest
          name: java-app1
          env:
          - name: JAVA_OPTS
            value: -XX:MaxRAMPercentage=80.0 -XX:+UseContainerSupport
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 500m
              memory: 700Mi
            requests:
              cpu: 200m
              memory: 400Mi
