apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-nginx
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    repoURL: https://github.com/argoproj/argocd-example-apps
    targetRevision: HEAD
    path: kustomize-guestbook
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
