version: "3.3"

# docker network create swsqnet --scope swarm  
# docker stack deploy --compose-file sonar-compose.yaml sqstack
# docker stack rm sqstack

services:
  swsq:
    image: sonarqube
    ports:
      - "9000:9000"
    networks:
      - swsqnet
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://swdbsq:5432/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
    volumes:
      - sonar_data:/opt/sonarqube/data
      - sonar_extensions:/opt/sonarqube/extensions
      - sonar_logs:/opt/sonarqube/logs
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 2048M
        reservations:
          cpus: '0.25'
          memory: 512M
      placement:
        constraints:
          - node.role == manager

  swdbsq:
    image: postgres
    ports:
      - "5442:5432"
    networks:
      - swsqnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

  nexus:
    image: sonatype/nexus3
    restart: always
    networks:
      - swsqnet
    volumes:
      - "nexus-data:/sonatype-work"
    ports:
      - "8081:8081"
      - "8085:8085"

volumes:
  sonar_data:
    external: true
  sonar_extensions:
    external: true
  sonar_logs:
    external: true
  postgresql:
    external: true
  postgresql_data:
    external: true
  nexus-data: 
    external: true

networks:
  swsqnet:
    # external: true
    driver: overlay
    attachable: true
