Vagrant.configure("2") do |config|

  config.vm.define "jenkins" do |jenkins|
    jenkins.vm.provider "docker" do |vm|
      vm.image = "jenkins/jenkins"
      vm.ports = ['8080:8080','50000:50000']
    end
  end

  config.vm.define "jvminfo" do |jvminfo|
    jvminfo.vm.provider "docker" do |vm|
      vm.image = "celeguim/jvminfo"
      vm.ports = ['8081:8080']
    end
  end


#   docker run -d -p 8081:8081 --name nexus sonatype/nexus3

end
